# Generated by Django 4.0.3 on 2023-04-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="employee_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
