# Generated by Django 4.0.3 on 2023-04-25 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0003_alter_automobilevo_vin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="is_vip",
        ),
    ]
